### ISSUE TITLE
Zeesa for real quit tf2 and internet?

### ISSUE THREAD

**Issue by Blueberryy** [p3tr1ch0r/ZeesHUD#2]
Will he come back?
And also can i implement localization for custom text that zeeshud has?

**Comment by RoonMoonlight** [comment]
@Blueberryy No, I guess he will never come back due to criticism towards him

**Comment by Blueberryy** [comment]
> @Blueberryy No, I guess he will never come back due to criticism towards him

I'm surprised how did he managed to survive in internet until these days. Pretty sad ;_;
