### ISSUE TITLE
[PSA] Preparation for breakage on next major update

### ISSUE THREAD

**Issue by RoonMoonlight** [p3tr1ch0r/ZeesHUD#9]
Important alert to all ZeesHUD-Undonored devs and contributors,

TF Team seems to be back, and they are [working on some sort of major update](https://www.teamfortress.com/post.php?id=189493), which might include changes which could break the hud.

> But this year, we're planning on shipping a full-on update-sized update — with items, maps, taunts, unusual effects, war paints and who knows what else?!

As you can see, new items might include new weapon items and balance patches coming very soon, with tons of bug fixes and changes which could result in a breakage.

We need to prepare for breakages, just in case. More news will come out this summer, so let's keep an eye out.

**Comment by usa1991** [comment]
So they will be an update for this hub right??

**Comment by RoonMoonlight** [comment]
> So they will be an update for this hub right??

Yes, update is inevitable if they make changes to the hud or new weapons

**Comment by usa1991** [comment]
So the creator of this hub already left the game right? So how is taking responsibility also it has been 2 years since it got an update.

**Comment by RoonMoonlight** [comment]
> So the creator of this hub already left the game right? So how is taking responsibility also it has been 2 years since it got an update.

I had the experience to modify the ZeesHUD named SaigonoHUD and it is discontinued... But I will try to make updates and pull request for broken ones since I have some knowledges about hud

All we need to do is looking at the file changes to the game

**Comment by usa1991** [comment]
ah ok, thx for the clarification, and good luck.

**Comment by RoonMoonlight** [comment]
Okay it seems there seems to be no HUD changes regarding TF2 from this summer update, so I am closing this in the meantime, and also author seems to be inactive anymore
